// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearMemory() {
  return window['go']['main']['App']['ClearMemory']();
}

export function ConnectAWG() {
  return window['go']['main']['App']['ConnectAWG']();
}

export function CreateClient(arg1) {
  return window['go']['main']['App']['CreateClient'](arg1);
}

export function CreateServer(arg1) {
  return window['go']['main']['App']['CreateServer'](arg1);
}

export function DeleteClient(arg1) {
  return window['go']['main']['App']['DeleteClient'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DeployServer() {
  return window['go']['main']['App']['DeployServer']();
}

export function DisconnectAWG() {
  return window['go']['main']['App']['DisconnectAWG']();
}

export function ExportActiveProfile() {
  return window['go']['main']['App']['ExportActiveProfile']();
}

export function ExportMemory() {
  return window['go']['main']['App']['ExportMemory']();
}

export function GetActiveClientID() {
  return window['go']['main']['App']['GetActiveClientID']();
}

export function GetActiveServerID() {
  return window['go']['main']['App']['GetActiveServerID']();
}

export function GetEffectiveAIPrompt() {
  return window['go']['main']['App']['GetEffectiveAIPrompt']();
}

export function GetLMStudioModels() {
  return window['go']['main']['App']['GetLMStudioModels']();
}

export function GetMemoryEntries(arg1) {
  return window['go']['main']['App']['GetMemoryEntries'](arg1);
}

export function GetMemoryStats() {
  return window['go']['main']['App']['GetMemoryStats']();
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HotSwapDomain(arg1) {
  return window['go']['main']['App']['HotSwapDomain'](arg1);
}

export function ImportMemory() {
  return window['go']['main']['App']['ImportMemory']();
}

export function ImportProfile() {
  return window['go']['main']['App']['ImportProfile']();
}

export function ListClients() {
  return window['go']['main']['App']['ListClients']();
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function RunDiagnostics() {
  return window['go']['main']['App']['RunDiagnostics']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SelectClient(arg1) {
  return window['go']['main']['App']['SelectClient'](arg1);
}

export function SelectServer(arg1) {
  return window['go']['main']['App']['SelectServer'](arg1);
}

export function SetUILanguage(arg1) {
  return window['go']['main']['App']['SetUILanguage'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function VerifyServer() {
  return window['go']['main']['App']['VerifyServer']();
}
