// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {profile} from '../models';
import {memory} from '../models';
import {main} from '../models';
import {diag} from '../models';

export function ClearMemory():Promise<void>;

export function ConnectAWG():Promise<void>;

export function CreateClient(arg1:string):Promise<profile.Profile>;

export function CreateServer(arg1:string):Promise<profile.Profile>;

export function DeleteClient(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function DeployServer():Promise<void>;

export function DisconnectAWG():Promise<void>;

export function ExportActiveProfile():Promise<void>;

export function ExportMemory():Promise<void>;

export function GetActiveClientID():Promise<string>;

export function GetActiveServerID():Promise<string>;

export function GetEffectiveAIPrompt():Promise<string>;

export function GetLMStudioModels():Promise<Array<string>>;

export function GetMemoryEntries(arg1:number):Promise<Array<memory.Entry>>;

export function GetMemoryStats():Promise<memory.Stats>;

export function GetProfile():Promise<profile.Profile>;

export function GetStatus():Promise<main.StatusInfo>;

export function HotSwapDomain(arg1:string):Promise<void>;

export function ImportMemory():Promise<void>;

export function ImportProfile():Promise<void>;

export function ListClients():Promise<Array<profile.ClientSummary>>;

export function ListServers():Promise<Array<profile.ServerSummary>>;

export function RunDiagnostics():Promise<diag.Report>;

export function SaveProfile(arg1:profile.Profile):Promise<void>;

export function SelectClient(arg1:string):Promise<void>;

export function SelectServer(arg1:string):Promise<void>;

export function SetUILanguage(arg1:string):Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;

export function VerifyServer():Promise<void>;
